MDScreen:
    name: "login"
    MDFloatLayout:
        md_bg_color: 1,1,0, .6
        Image:
            source: 'USUARIO.png'
            size_hint: 0.5, 0.5
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
        MDLabel:
            text: "LOGIN"
            pos_hint: {'center_x':0.8, 'center_y':0.9}
            haling:'center'
            theme_text_color:'Custom'
            text_color: 1,1,1,1
            font_size: '45sp'
            font_name:'Bubblegum.ttf'
