MDScreen:
    name: "splash"
    MDFloatLayout:
        md_bg_color: 0,1,0, .6
        Image:
            source: "LOGO.png"
            size_hint: 0.9, 0.9
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        MDLabel:
            text: "SAWA BUS"
            pos_hint: {'center_x':0.65, 'center_y':0.3}
            haling:'center'
            theme_text_color:'Custom'
            text_color: 1,1,1,1
            font_size: '45sp'
            font_name:'Bubblegum.ttf'